site_name: Gluster Docs
site_url: http://docs.gluster.org
site_description: Project documentation for Gluster Filesystem

repo_url: https://github.com/gluster/glusterdocs/
docs_dir: .

pages:
- Home: index.md
- Getting started with GlusterFS:
  - Quick Start Guide: Quick-Start-Guide/Quickstart.md
  - Architecture: Quick-Start-Guide/Architecture.md
- Install Guide:
  - Overview: Install-Guide/Overview.md
  - Common Criteria: Install-Guide/Common_criteria.md
  - Setting up in virtual machines: Install-Guide/Setup_virt.md
  - Setting up on physical servers: Install-Guide/Setup_Bare_metal.md
  - Deploying in AWS: Install-Guide/Setup_aws.md
  - Install: Install-Guide/Install.md
  - Compiling RPMS: Install-Guide/compiling-rpms.md
  - Community Packages: Install-Guide/Community_Packages.md
  - Configure: Install-Guide/Configure.md
- Presentations: presentations/index.md
- Administrator Guide:
  - Index: Administrator Guide/index.md
  - GlusterFS Introduction: Administrator Guide/GlusterFS Introduction.md
  - Did You Know: Administrator Guide/Did You Know.md
  - Managing the Gluster Service: Administrator Guide/Start Stop Daemon.md
  - Managing Trusted Storage Pools: Administrator Guide/Storage Pools.md
  - Setting Up Storage:
     - Setting Up Storage : Administrator Guide/setting-up-storage.md
     - Brick Naming Conventions: Administrator Guide/Brick Naming Conventions.md
     - Formatting and Mounting Bricks: Administrator Guide/formatting-and-mounting-bricks.md
     - Access Control Lists: Administrator Guide/Access Control Lists.md
  - Handling of users that belong to many groups: Administrator Guide/Handling-of-users-with-many-groups.md
  - Setting Up Volumes: Administrator Guide/Setting Up Volumes.md
  - Setting Up Clients: Administrator Guide/Setting Up Clients.md
  - Managing Volumes: Administrator Guide/Managing Volumes.md
  - Building QEMU with gfapi For Debian Based Systems: Administrator Guide/Building QEMU With gfapi For Debian Based Systems.md
  - GlusterFS Filter: Administrator Guide/GlusterFS Filter.md
  - Logging: Administrator Guide/Logging.md
  - Geo Replication: Administrator Guide/Geo Replication.md
  - Directory Quota: Administrator Guide/Directory Quota.md
  - Managing Snapshots: Administrator Guide/Managing Snapshots.md
  - Monitoring Workload: Administrator Guide/Monitoring Workload.md
  - Object Storage: Administrator Guide/Object Storage.md
  - GlusterFS Cinder: Administrator Guide/GlusterFS Cinder.md
  - GlusterFS Keystone Quickstart: Administrator Guide/GlusterFS Keystone Quickstart.md
  - Gluster On ZFS: Administrator Guide/Gluster On ZFS.md
  - Configuring Bareos to store backups on Gluster: Administrator Guide/Bareos.md
  - SSL: Administrator Guide/SSL.md
  - Puppet Gluster: Administrator Guide/Puppet.md
  - RDMA Transport: Administrator Guide/RDMA Transport.md
  - GlusterFS iSCSI: Administrator Guide/GlusterFS iSCSI.md
  - Configuring NFS-Ganesha server: Administrator Guide/NFS-Ganesha GlusterFS Integration.md
  - Linux Kernel Tuning: Administrator Guide/Linux Kernel Tuning.md
  - Troubleshooting: Administrator Guide/Troubleshooting.md
  - Network Configurations Techniques: Administrator Guide/Network Configurations Techniques.md
  - Performance Testing: Administrator Guide/Performance Testing.md
  - Export and Netgroup Authentication: Administrator Guide/Export And Netgroup Authentication.md
  - Consul integration: Administrator Guide/Consul.md
  - Split brain and ways to deal with it: Administrator Guide/Split brain and ways to deal with it.md
  - Arbiter volumes and quorum options: Administrator Guide/arbiter-volumes-and-quorum.md
  - Trash for GlusterFS: Administrator Guide/Trash.md
  - Mandatory Locks: Administrator Guide/Mandatory Locks.md
  - GlusterFS coreutilities: Administrator Guide/GlusterFS Coreutils.md
  - Events APIs: Administrator Guide/Events APIs.md
- CLI Reference:
  - Overview: CLI-Reference/cli-main.md
- Developers Guide:
  - Developers Home: Developer-guide/Developers-Index.md
  - Simplified Development Workflow : Developer-guide/Simplified-Development-Workflow.md
  - Development-Workflow : Developer-guide/Development-Workflow.md
  - Compiling RPMS from GIT Source : Developer-guide/Compiling-RPMS.md
  - Build and Install GlusterFS : Developer-guide/Building-GlusterFS.md
  - Project Ideas : Developer-guide/Projects.md
  - EasyFix bugs : Developer-guide/Easy-Fix-Bugs.md
  - Fixing issues reported by tools for static code analysis : Developer-guide/Fixing-issues-reported-by-tools-for-static-code-analysis.md
  - Backport Wishlist : Developer-guide/Backport-Wishlist.md
  - Backport Guidelines : Developer-guide/Backport-Guidelines.md
- Contributors Guide:
  - Index: Contributors-Guide/Index.md
  - Bug Reporting Guidelines : Contributors-Guide/Bug-Reporting-Guidelines.md
  - Bug Triage : Contributors-Guide/Bug-Triage.md
  - Bug report Cycle : Contributors-Guide/Bug-report-Life-Cycle.md
  - Bug Reporting Template : Contributors-Guide/Bug-reporting-template.md
  - GlusterFS Release process : Contributors-Guide/GlusterFS-Release-process.md
  - Guidelines For Maintainers : Contributors-Guide/Guidelines-For-Maintainers.md
  - Adding your gluster blog : Contributors-Guide/Adding-your-blog.md
- Ops Guide:
  - Index: Ops-Guide/Overview.md
  - Tools: Ops-Guide/Tools.md
- Upgrade-Guide:
  - Upgrade-Guide Index: Upgrade-Guide/README.md
  - Op-version: Upgrade-Guide/op_version.md
  - Upgrade to 3.5: Upgrade-Guide/upgrade_to_3.5.md
  - Upgrade to 3.6: Upgrade-Guide/upgrade_to_3.6.md
  - Upgrade to 3.7: Upgrade-Guide/upgrade_to_3.7.md
  - Upgrade to 3.8: Upgrade-Guide/upgrade_to_3.8.md
  - Upgrade to 3.9: Upgrade-Guide/upgrade_to_3.9.md
  - Upgrade to 3.10: Upgrade-Guide/upgrade_to_3.10.md
  - Upgrade to 3.11: Upgrade-Guide/upgrade_to_3.11.md
  - Upgrade to 3.12: Upgrade-Guide/upgrade_to_3.12.md
  - Upgrade to 3.13: Upgrade-Guide/upgrade_to_3.13.md
- Release Notes:
  - index: release-notes/index.md
  - 3.13.1: release-notes/3.13.1.md
  - 3.13.0: release-notes/3.13.0.md
  - 3.12.4: release-notes/3.12.4.md
  - 3.12.3: release-notes/3.12.3.md
  - 3.12.2: release-notes/3.12.2.md
  - 3.12.1: release-notes/3.12.1.md
  - 3.12.0: release-notes/3.12.0.md
  - 3.11.3: release-notes/3.11.3.md
  - 3.11.2: release-notes/3.11.2.md
  - 3.11.1: release-notes/3.11.1.md
  - 3.11.0: release-notes/3.11.0.md
  - 3.10.8: release-notes/3.10.8.md
  - 3.10.7: release-notes/3.10.7.md
  - 3.10.6: release-notes/3.10.6.md
  - 3.10.5: release-notes/3.10.5.md
  - 3.10.4: release-notes/3.10.4.md
  - 3.10.3: release-notes/3.10.3.md
  - 3.10.2: release-notes/3.10.2.md
  - 3.10.1: release-notes/3.10.1.md
  - 3.10.0: release-notes/3.10.0.md
  - 3.9.0: release-notes/3.9.0.md
  - 3.7.1: release-notes/3.7.1.md
  - 3.7.0: release-notes/3.7.0.md
  - 3.6.3: release-notes/3.6.3.md
  - 3.6.0: release-notes/3.6.0.md
  - 3.5.4: release-notes/3.5.4.md
  - 3.5.3: release-notes/3.5.3.md
  - 3.5.2: release-notes/3.5.2.md
  - 3.5.1: release-notes/3.5.1.md
  - 3.5.0: release-notes/3.5.0.md
- GlusterFS Tools:
  - GlusterFS Tools List: GlusterFS Tools/README.md
  - glusterfind: GlusterFS Tools/glusterfind.md
  - gfind missing files: GlusterFS Tools/gfind_missing_files.md
- Troubleshooting Guide:
  - Index: Troubleshooting/README.md
  - Components:
    - Troubleshooting CLI and glusterd: Troubleshooting/troubleshooting-glusterd.md
    - Troubleshooting Geo-replication: Troubleshooting/troubleshooting-georep.md
    - Troubleshooting gNFS: Troubleshooting/troubleshooting-gnfs.md
    - Troubleshooting Split-Brains: Troubleshooting/resolving-splitbrain.md
  - Issues:
    - Debugging Memory Leaks: Troubleshooting/troubleshooting-memory.md
  - Tools:
    - Statedump: Troubleshooting/statedump.md
    - gfid to path: Troubleshooting/gfid-to-path.md
- Glossary: ./glossary.md
- Google Site Verification: ./google64817fdc11b2f6b6.html

theme: readthedocs
theme_dir: glustertheme
extra_javascript:
- js/fix-docs.js
