site_name: Gluster Docs
site_url: http://www.gluster.org
site_description: Project documentation for Gluster Filesystem

repo_url: https://github.com/gluster/glusterdocs/
docs_dir: .

pages:
- Home: index.md
- Gluster File System Quickstart:
  - Quickstart Guide: Quick-Start-Guide/Quickstart.md
- Gluster Concepts and Terminology:
  - Terminologies: Quick-Start-Guide/Terminologies.md
  - Glossary: Administrator Guide/glossary.md
  - Architecture: Quick-Start-Guide/Architecture.md
  - Design: Concepts-Guide/Design.md
  - Security: Concepts-Guide/Security.md
  - Scaling: Concepts-Guide/Scaling.md
  - Resiliency: Concepts-Guide/Resiliency.md
  - Presentations: presentations/index.md
- Installation Guide:
  - Overview: Install-Guide/Overview.md
  - Common Criteria: Install-Guide/Common_criteria.md
  - Server setup:
    - Setting up in virtual machines: Install-Guide/Setup_virt.md
    - Setting up on physical servers: Install-Guide/Setup_Bare_metal.md
    - Deploying on AWS: Install-Guide/Setup_aws.md
  - Installing:  Install-Guide/Install.md
  - Adding Community Packages: Install-Guide/Community_Packages.md
  - Configuring Gluster: Install-Guide/Configure.md
- Administrator Guide:
  - GlusterFS Introduction: Administrator Guide/GlusterFS Introduction.md
  - Architecture: Quick-Start-Guide/Architecture.md
  - Glossary: Administrator Guide/glossary.md
  - Creating and configuring your environment:
    - Storage Pools: Administrator Guide/Storage Pools.md
    - Access Control Lists: Administrator Guide/Access Control Lists.md
    - Setting Up Clients: Administrator Guide/Setting Up Clients.md
    - Setting Up Volumes: Administrator Guide/Setting Up Volumes.md
    - Brick Naming Conventions: Administrator Guide/Brick Naming Conventions.md
    - Geo Replication: Administrator Guide/Geo Replication.md
    - Directory Quota: Administrator Guide/Directory Quota.md
    - Linux Kernel Tuning: Administrator Guide/Linux Kernel Tuning.md
  - Gluster Administration Tools:
    - Gluster Console Guide: Administrator Guide/Console.md
    - Events APIs: Administrator Guide/Events APIs.md
    - SSL: Administrator Guide/SSL.md
  - Managing Gluster:
    - Managing the Gluster Service: Administrator Guide/Start Stop Daemon.md
    - Handling of users that belong to many groups: Administrator Guide/Handling-of-users-with-many-groups.md
    - Managing Volumes: Administrator Guide/Managing Volumes.md
    - Managing Snapshots: Administrator Guide/Managing Snapshots.md
    - Monitoring Workload: Administrator Guide/Monitoring Workload.md
    - GlusterFS Filter: Administrator Guide/GlusterFS Filter.md
    - Object Storage: Administrator Guide/Object Storage.md
    - GlusterFS coreutilities: Administrator Guide/GlusterFS Coreutils.md
    - Resolving Peer Rejected State: Administrator Guide/Resolving Peer Rejected.md
    - Network Configurations Techniques: Administrator Guide/Network Configurations Techniques.md
    - Performance Testing: Administrator Guide/Performance Testing.md
    - Export and Netgroup Authentication: Administrator Guide/Export And Netgroup Authentication.md
    - Configuring NFS-Ganesha server: Administrator Guide/NFS-Ganesha GlusterFS Integration.md
    - Arbiter volumes and quorum options: Administrator Guide/arbiter-volumes-and-quorum.md
    - Trash for GlusterFS: Administrator Guide/Trash.md
    - Mandatory Locks: Administrator Guide/Mandatory Locks.md
  - Using Gluster with other software:
    - GlusterFS Cinder: Administrator Guide/GlusterFS Cinder.md
    - GlusterFS Keystone Quickstart: Administrator Guide/GlusterFS Keystone Quickstart.md
    - Hadoop: Administrator Guide/Hadoop.md
    - Gluster On ZFS: Administrator Guide/Gluster On ZFS.md
    - Configuring Bareos to store backups on Gluster: Administrator Guide/Bareos.md
    - Puppet Gluster: Administrator Guide/Puppet.md
    - RDMA Transport: Administrator Guide/RDMA Transport.md
    - GlusterFS iSCSI: Administrator Guide/GlusterFS iSCSI.md
    - Configuring NFS-Ganesha server: Administrator Guide/NFS-Ganesha GlusterFS Integration.md
    - Building QEMU with gfapi For Debian Based Systems: Administrator Guide/Building QEMU With gfapi For Debian Based Systems.md
    - Compiling RPMS: Administrator Guide/Compiling RPMS.md
  - Logging and troubleshooting with Gluster:
    - Did You Know: Administrator Guide/Did You Know.md
    - Logging: Administrator Guide/Logging.md
    - Troubleshooting: Administrator Guide/Troubleshooting.md
    - Split brain and ways to deal with it: Administrator Guide/Split brain and ways to deal with it.md
- Developers Guide:
  - Developers Home: Developer-guide/Developers-Index.md
  - Simplified Development Workflow : Developer-guide/Simplified-Development-Workflow.md
  - Development-Workflow : Developer-guide/Development-Workflow.md
  - Compiling RPMS from GIT Source : Developer-guide/Compiling-RPMS.md
  - Build and Install GlusterFS : Developer-guide/Building-GlusterFS.md
  - Project Ideas : Developer-guide/Projects.md
  - EasyFix bugs : Developer-guide/Easy-Fix-Bugs.md
  - Fixing issues reported by tools for static code analysis : Developer-guide/Fixing-issues-reported-by-tools-for-static-code-analysis.md
  - Backport Wishlist : Developer-guide/Backport-Wishlist.md
  - Backport Guidelines : Developer-guide/Backport-Guidelines.md
- Contributors Guide:
  - Index: Contributors-Guide/Index.md
  - Bug Reporting Guidelines : Contributors-Guide/Bug-Reporting-Guidelines.md
  - Bug Triage : Contributors-Guide/Bug-Triage.md
  - Bug report Cycle : Contributors-Guide/Bug-report-Life-Cycle.md
  - Bug Reporting Template : Contributors-Guide/Bug-reporting-template.md
  - GlusterFS Release process : Contributors-Guide/GlusterFS-Release-process.md
  - Guidelines For Maintainers : Contributors-Guide/Guidelines-For-Maintainers.md
  - Adding your gluster blog : Contributors-Guide/Adding-your-blog.md
- Operations Guide:
  - Index: Ops-Guide/Overview.md
  - Tools: Ops-Guide/Tools.md
- Upgrade Guide:
  - Upgrade-Guide Contents: Upgrade-Guide/README.md
  - Op-version: Upgrade-Guide/op_version.md
  - Upgrade to 3.5: Upgrade-Guide/upgrade_to_3.5.md
  - Upgrade to 3.6: Upgrade-Guide/upgrade_to_3.6.md
  - Upgrade to 3.7: Upgrade-Guide/upgrade_to_3.7.md
  - Upgrade to 3.9: Upgrade-Guide/upgrade_to_3.9.md
  - Upgrade to 3.10: Upgrade-Guide/upgrade_to_3.10.md
  - Upgrade to 3.11: Upgrade-Guide/upgrade_to_3.11.md
- Release Notes:
  - index: release-notes/index.md
  - 3.11.0: release-notes/3.11.0.md
  - 3.10.1: release-notes/3.10.1.md
  - 3.10.0: release-notes/3.10.0.md
  - 3.9.0: release-notes/3.9.0.md
  - 3.7.1: release-notes/3.7.1.md
  - 3.7.0: release-notes/3.7.0.md
  - 3.6.3: release-notes/3.6.3.md
  - 3.6.0: release-notes/3.6.0.md
  - 3.5.4: release-notes/3.5.4.md
  - 3.5.3: release-notes/3.5.3.md
  - 3.5.2: release-notes/3.5.2.md
  - 3.5.1: release-notes/3.5.1.md
  - 3.5.0: release-notes/3.5.0.md
- GlusterFS Tools:
  - GlusterFS Tools List: GlusterFS Tools/README.md
  - glusterfind: GlusterFS Tools/glusterfind.md
  - gfind missing files: GlusterFS Tools/gfind_missing_files.md
- Troubleshooting Guide:
  - Index: Troubleshooting/README.md
  - gfid to path: Troubleshooting/gfid-to-path.md
  - Split Brain (Manual): Troubleshooting/split-brain.md
  - Split Brain (Auto): Troubleshooting/heal-info-and-split-brain-resolution.md
  - Statedump: Troubleshooting/statedump.md
- Google Site Verification: ./google64817fdc11b2f6b6.html
- Templates:
  - Procedure: Templates/procedure_template.md
  - Best Practice: Templates/best_practice_template.md
  - Concept: Templates/concept_template.md

theme: readthedocs
