site_name: Gluster Docs
site_url: http://www.gluster.org
site_description: Project documentation for Gluster Filesystem

repo_url: https://github.com/gluster/glusterdocs/
docs_dir: .

pages:
- Home: index.md
- Getting started with GlusterFS:
  - Quick start Guide: Quick-Start-Guide/Quickstart.md
  - Terminologies: Quick-Start-Guide/Terminologies.md
  - Architecture: Quick-Start-Guide/Architecture.md
- Install Guide:
  - Overview: Install-Guide/Overview.md
  - Common Criteria: Install-Guide/Common_criteria.md
  - Quick start to Install: Install-Guide/Quick_start.md
  - Setting up in virtual machines: Install-Guide/Setup_virt.md
  - Setting up on physical servers: Install-Guide/Setup_Bare_metal.md
  - Deploying in AWS: Install-Guide/Setup_aws.md
  - Install: Install-Guide/Install.md
  - Configure: Install-Guide/Configure.md
- Presentations: presentations/index.md
- Administrator Guide:
  - Index: Administrator Guide/README.md
  - GlusterFS Introduction: Administrator Guide/GlusterFS Introduction.md
  - Glossary: Administrator Guide/glossary.md
  - Did You Know: Administrator Guide/Did You Know.md
  - Storage Pools: Administrator Guide/Storage Pools.md
  - Compiling RPMS: Administrator Guide/Compiling RPMS.md
  - Managing the Gluster Service: Administrator Guide/Start Stop Daemon.md
  - Gluster Console Guide: Administrator Guide/Console.md
  - Access Control Lists: Administrator Guide/Access Control Lists.md
  - Setting Up Clients: Administrator Guide/Setting Up Clients.md
  - Setting Up Volumes: Administrator Guide/Setting Up Volumes.md
  - Managing Volumes: Administrator Guide/Managing Volumes.md
  - Building QEMU with gfapi For Debian Based Systems: Administrator Guide/Building QEMU With gfapi For Debian Based Systems.md
  - GlusterFS Filter: Administrator Guide/GlusterFS Filter.md
  - Resolving Peer Rejected State: Administrator Guide/Resolving Peer Rejected.md
  - Logging: Administrator Guide/Logging.md
  - Brick Naming Conventions: Administrator Guide/Brick Naming Conventions.md
  - Geo Replication: Administrator Guide/Geo Replication.md
  - Distributed Geo Replication: Administrator Guide/Distributed Geo Replication.md
  - Directory Quota: Administrator Guide/Directory Quota.md
  - Managing Snapshots: Administrator Guide/Managing Snapshots.md
  - Monitoring Workload: Administrator Guide/Monitoring Workload.md
  - Object Storage: Administrator Guide/Object Storage.md
  - GlusterFS Cinder: Administrator Guide/GlusterFS Cinder.md
  - GlusterFS Keystone Quickstart: Administrator Guide/GlusterFS Keystone Quickstart.md
  - Hadoop: Administrator Guide/Hadoop.md
  - Gluster On ZFS: Administrator Guide/Gluster On ZFS.md
  - Configuring Bareos to store backups on Gluster: Administrator Guide/Bareos.md
  - SSL: Administrator Guide/SSL.md
  - Puppet Gluster: Administrator Guide/Puppet.md
  - RDMA Transport: Administrator Guide/RDMA Transport.md
  - GlusterFS iSCSI: Administrator Guide/GlusterFS iSCSI.md
  - Configuring HA NFS server: Administrator Guide/Configuring HA NFS Server.md
  - Linux Kernel Tuning: Administrator Guide/Linux Kernel Tuning.md
  - Troubleshooting: Administrator Guide/Troubleshooting.md
  - Network Configurations Techniques: Administrator Guide/Network Configurations Techniques.md
  - Performance Testing: Administrator Guide/Performance Testing.md
  - Export and Netgroup Authentication: Administrator Guide/Export And Netgroup Authentication.md
- Developers Guide:
  - Developers Home: Developer-guide/Developers Index.md
  - Simplified Development Workflow: Developer-guide/Simplified Development Workflow.md
  - Development Workflow: Developer-guide/Development Workflow.md
  - Coding Standards: Developer-guide/coding-standard.md
  - Compiling RPMS: Developer-guide/Compiling RPMS.md
  - Building GlusterFS: Developer-guide/Building GlusterFS.md
  - Projects: Developer-guide/Projects.md
  - Language Bindings: Developer-guide/Language Bindings.md
  - Easy Fix Bugs: Developer-guide/Easy Fix Bugs.md
  - Fixing issues for static code analysis: Developer-guide/Fixing issues reported by tools for static code analysis.md
  - Backport Wishlist: Developer-guide/Backport Wishlist.md
  - Backport Guidelines: Developer-guide/Backport Guidelines.md
  - Adding File Operations: Developer-guide/adding-fops.md
  - Automatic File Replication: Developer-guide/afr.md
  - History of Locking in AFR: Developer-guide/afr-locks-evolution.md
  - Self heal Daemon: Developer-guide/afr-self-heal-daemon.md
  - inode datastructure: Developer-guide/datastructure-inode.md
  - iobuf datastructure: Developer-guide/datastructure-iobuf.md
  - mem-pool datastructure: Developer-guide/datastructure-mem-pool.md
  - gfapi Symbol Versions: Developer-guide/gfapi-symbol-versions.md
  - Daemon Management Framework: Developer-guide/daemon-management-framework.md
  - Block Device Translator: Developer-guide/bd-xlator.md
  - Write Behind Translator: Developer-guide/write-behind.md
  - Translator Development: Developer-guide/translator-development.md
  - Storage/posix Translator: Developer-guide/posix.md
  - Compression Translator: Developer-guide/network_compression.md
  - Unit Tests in GlusterFS: Developer-guide/unittest.md
  - Using Gluster Test Framework: Developer-guide/Using Gluster Test Framework.md
  - Jenkins Infrastructure: Developer-guide/Jenkins Infrastructure.md
  - Jenkins Manual Setup: Developer-guide/Jenkins Manual Setup.md
  - Coredump Analysis: Developer-guide/coredump-analysis.md
  - Bug Reporting Guidelines: Developer-guide/Bug Reporting Guidelines.md
  - Bug Triage Guidelines: Developer-guide/Bug Triage.md
  - Bug Report Life Cycle: Developer-guide/Bug report Life Cycle.md
  - Guidelines for Maintainers: Developer-guide/Guidelines For Maintainers.md
  - Versioning: Developer-guide/versioning.md
  - GlusterFS Release Process: Developer-guide/GlusterFS Release process.md
  - Bug Reporting Template: Developer-guide/Bug reporting template.md
- Upgrade-Guide:
  - Upgrade-Guide Index: Upgrade-Guide/README.md
  - Upgrade to 3.5: Upgrade-Guide/upgrade_to_3.5.md
  - Upgrade to 3.6: Upgrade-Guide/upgrade_to_3.6.md
  - Upgrade to 3.7: Upgrade-Guide/Upgrade to 3.7.md
- Release Notes:
  - index: release-notes/index.md
  - 3.7.1: release-notes/3.7.1.md
  - 3.7.0: release-notes/3.7.0.md
  - 3.6.3: release-notes/3.6.3.md
  - 3.6.0: release-notes/3.6.0.md
  - 3.5.4: release-notes/3.5.4.md
  - 3.5.3: release-notes/3.5.3.md
  - 3.5.2: release-notes/3.5.2.md
  - 3.5.1: release-notes/3.5.1.md
  - 3.5.0: release-notes/3.5.0.md
- GlusterFS Tools:
  - GlusterFS Tools List: GlusterFS Tools/README.md
  - glusterfind: GlusterFS Tools/glusterfind.md
  - gfind missing files: GlusterFS Tools/gfind_missing_files.md
- Troubleshooting Guide:
  - Index: Troubleshooting/README.md
  - gfid to path: Troubleshooting/gfid-to-path.md
  - Split Brain: Troubleshooting/split-brain.md
  - Statedump: Troubleshooting/statedump.md
- Google Site Verification: ./google64817fdc11b2f6b6.html

theme: readthedocs
