site_name: Gluster Docs
site_url: http://www.gluster.org
site_description: Project documentation for Gluster Filesystem

repo_url: https://github.com/humblec/gluster-docs/

pages:
- ['index.md', 'Home']
- ['Quick-Start-Guide/Quickstart.md', 'Quickstart Guide', 'Quickstart']
- ['Quick-Start-Guide/Terminologies.md', 'Quickstart Guide', 'Terminologies']
- ['Quick-Start-Guide/Architecture.md', 'Quickstart Guide', 'Architecture']
- ['Install-Guide/Overview.md', 'Install Guide', 'Overview']
- ['Install-Guide/Common_criteria.md', 'Install Guide', 'Common Criteria']
- ['Install-Guide/Quick_start.md', 'Install Guide', 'Quick start to Install']
- ['Install-Guide/Setup_aws.md', 'Install Guide', 'Deploying in AWS']
- ['Install-Guide/Setup_virt.md', 'Install Guide', 'Setting up in virtual machines']
- ['Install-Guide/Setup_Bare_metal.md', 'Install Guide', 'Setting up on physical servers']
- ['Install-Guide/Install.md', 'Install Guide', 'Install']
- ['Install-Guide/Configure.md', 'Install Guide', 'Configure']
- ['Administrator Guide/README.md', 'Administrator Guide', 'Admin Home']
- ['Administrator Guide/GlusterFS Introduction.md', 'Administrator Guide', 'GlusterFS Introduction']
- ['Administrator Guide/glossary.md', 'Administrator Guide', 'Glossary']
- ['Administrator Guide/Did You Know.md', 'Administrator Guide', 'Did You Know']
- ['Administrator Guide/Storage Pools.md', 'Administrator Guide', 'Storage Pools']
- ['Administrator Guide/Compiling RPMS.md', 'Administrator Guide', 'Compiling RPMS']
- ['Administrator Guide/Start Stop Daemon.md', 'Administrator Guide', 'Managing the Gluster Service']
- ['Administrator Guide/Console.md', 'Administrator Guide', 'Gluster Console Guide']
- ['Administrator Guide/Access Control Lists.md', 'Administrator Guide', 'Access Control Lists']
- ['Administrator Guide/Setting Up Clients.md', 'Administrator Guide', 'Setting Up Clients']
- ['Administrator Guide/Setting Up Volumes.md', 'Administrator Guide', 'Setting Up Volumes']
- ['Administrator Guide/Managing Volumes.md', 'Administrator Guide', 'Managing Volumes']
- ['Administrator Guide/Building QEMU With gfapi For Debian Based Systems.md', 'Administrator Guide', 'Building QEMU With gfapi For Debian Based Systems']
- ['Administrator Guide/GlusterFS Filter.md', 'Administrator Guide', 'GlusterFS Filter']
- ['Administrator Guide/Resolving Peer Rejected.md', 'Administrator Guide', 'Resolving Peer Rejected State']
- ['Administrator Guide/Logging.md', 'Administrator Guide', 'Logging']
- ['Administrator Guide/Brick Naming Conventions.md', 'Administrator Guide', 'Brick Naming Conventions']
- ['Administrator Guide/Geo Replication.md', 'Administrator Guide', 'Geo Replication']
- ['Administrator Guide/Distributed Geo Replication.md', 'Administrator Guide', 'Distributed Geo Replication']
- ['Administrator Guide/Directory Quota.md', 'Administrator Guide', 'Directory Quota']
- ['Administrator Guide/Managing Snapshots.md', 'Administrator Guide', 'Managing Snapshots']
- ['Administrator Guide/Monitoring Workload.md', 'Administrator Guide', 'Monitoring Workload']
- ['Administrator Guide/Object Storage.md', 'Administrator Guide', 'Object Storage']
- ['Administrator Guide/GlusterFS Cinder.md', 'Administrator Guide', 'GlusterFS Cinder']
- ['Administrator Guide/GlusterFS Keystone Quickstart.md', 'Administrator Guide', 'GlusterFS Keystone Quickstart']
- ['Administrator Guide/Hadoop.md', 'Administrator Guide', 'Hadoop']
- ['Administrator Guide/Gluster On ZFS.md', 'Administrator Guide', 'Gluster On ZFS']
- ['Administrator Guide/SSL.md', 'Administrator Guide', 'SSL']
- ['Administrator Guide/Puppet.md', 'Administrator Guide', 'Puppet Gluster']
- ['Administrator Guide/RDMA Transport.md', 'Administrator Guide', 'RDMA Transport']
- ['Administrator Guide/GlusterFS iSCSI.md', 'Administrator Guide', 'GlusterFS iSCSI']
- ['Administrator Guide/Linux Kernel Tuning.md', 'Administrator Guide', 'Linux Kernel Tuning']
- ['Administrator Guide/Troubleshooting.md', 'Administrator Guide', 'Troubleshooting']
- ['Administrator Guide/Network Configurations Techniques.md', 'Administrator Guide', 'Network Configurations Techniques']
- ['Administrator Guide/Performance Testing.md', 'Administrator Guide', 'Performance Testing']
- ['Developer-guide/Developers Index.md', 'Developers Guide', 'Developers Home']
- ['Developer-guide/Simplified Development Workflow.md', 'Developers Guide', 'Simplified Development Workflow']
- ['Developer-guide/Development Workflow.md', 'Developers Guide', 'Development Workflow']
- ['Developer-guide/coding-standard.md', 'Developers Guide', 'Coding Standards']
- ['Developer-guide/Compiling RPMS.md', 'Developers Guide', 'Compiling RPMS']
- ['Developer-guide/Building GlusterFS.md', 'Developers Guide', 'Building GlusterFS']
- ['Developer-guide/Projects.md', 'Developers Guide', 'Projects']
- ['Developer-guide/Language Bindings.md', 'Developers Guide', 'Language Bindings']
- ['Developer-guide/Easy Fix Bugs.md', 'Developers Guide', 'Easy Fix Bugs']
- ['Developer-guide/Fixing issues reported by tools for static code analysis.md', 'Developers Guide', 'Fixing issues for static code analysis']
- ['Developer-guide/Backport Wishlist.md', 'Developers Guide', 'Backport Wishlist']
- ['Developer-guide/Backport Guidelines.md', 'Developers Guide', 'Backport Guidelines']
- ['Developer-guide/adding-fops.md', 'Developers Guide', 'Adding File Operations']
- ['Developer-guide/afr.md', 'Developers Guide', 'Automatic File Replication']
- ['Developer-guide/afr-locks-evolution.md', 'Developers Guide', 'History of Locking in AFR']
- ['Developer-guide/afr-self-heal-daemon.md', 'Developers Guide', 'Seal heal Daemon']
- ['Developer-guide/datastructure-inode.md', 'Developers Guide', 'inode datastructure']
- ['Developer-guide/datastructure-iobuf.md', 'Developers Guide', 'iobuf datastructure']
- ['Developer-guide/datastructure-mem-pool.md', 'Developers Guide', 'mem-pool datastructure']
- ['Developer-guide/gfapi-symbol-versions.md', 'Developers Guide', 'gfapi Symbol Versions']
- ['Developer-guide/daemon-management-framework.md', 'Developers Guide', 'Daemon Management Framework']
- ['Developer-guide/bd-xlator.md', 'Developers Guide', 'Block Device Translator']
- ['Developer-guide/write-behind.md', 'Developers Guide', 'Write Behind Translator']
- ['Developer-guide/translator-development.md', 'Developers Guide', 'Translator Development']
- ['Developer-guide/posix.md', 'Developers Guide', 'Storage/posix Translator']
- ['Developer-guide/network_compression.md', 'Developers Guide', 'Compression Translator']
- ['Developer-guide/unittest.md', 'Developers Guide', 'Unit Tests in GlusterFS']
- ['Developer-guide/Using Gluster Test Framework.md', 'Developers Guide', 'Using Gluster Test Framework']
- ['Developer-guide/Jenkins Infrastructure.md', 'Developers Guide', 'Jenkins Infrastructure']
- ['Developer-guide/Jenkins Manual Setup.md', 'Developers Guide', 'Jenkins Manual Setup']
- ['Developer-guide/Bug Reporting Guidelines.md', 'Developers Guide', 'Bug Reporting Guidelines']
- ['Developer-guide/Bug Triage.md', 'Developers Guide', 'Bug Triage Guidelines']
- ['Developer-guide/Bug report Life Cycle.md', 'Developers Guide', 'Bug Report Life Cycle']
- ['Developer-guide/Guidelines For Maintainers.md', 'Developers Guide', 'Guidelines for Maintainers']
- ['Developer-guide/versioning.md', 'Developers Guide', 'Versioning']
- ['Developer-guide/GlusterFS Release process.md', 'Developers Guide', 'GlusterFS Release Process']
- ['Developer-guide/Bug reporting template.md', 'Developers Guide', 'Bug Reporting Template']
- ['Upgrade-Guide/README.md', 'Upgrade-Guide', 'Upgrade-Guide Home']
- ['Upgrade-Guide/upgrade_to_3.5.md', 'Upgrade-Guide', 'Upgrade to 3.5']
- ['Upgrade-Guide/upgrade_to_3.6.md', 'Upgrade-Guide', 'Upgrade to 3.6']
- ['Upgrade-Guide/Upgrade to 3.7.md', 'Upgrade-Guide', 'Upgrade to 3.7']
- ['Features/README.md', 'Features', 'Features Home']
- ['Features/afr-arbiter-volumes.md', 'Features', 'AFR Arbiter Volumes']
- ['Features/bitrot-docs.md', 'Features', 'bitrot docs']
- ['Features/memory-usage.md', 'Features', 'bitrot memory usage']
- ['Features/object-versioning.md', 'Features', 'Object Versioning']
- ['Features/shard.md', 'Features', 'shard']
- ['Features/upcall.md', 'Features', 'upcall']
- ['Features/quota-object-count.md', 'Features', 'quota object count']
- ['Features/glusterfs_nfs-ganesha_integration.md', 'Features', 'nfs-ganesha integration']
- ['Features/tier.md', 'Features', 'tiering']
- ['Features/afr-statistics.md', 'Features', 'AFR Statistics']
- ['Features/afr-v1.md', 'Features', 'AFR ver1']
- ['Features/brick-failure-detection.md', 'Features', 'Brick Failure Detection']
- ['Features/file-snapshot.md', 'Features', 'File Snapshot']
- ['Features/gfid-access.md', 'Features', 'gfid Access']
- ['Features/quota-scalability.md', 'Features', 'Quota Scalability']
- ['Features/readdir-ahead.md', 'Features', 'readdir ahead']
- ['Features/zerofill.md', 'Features', 'zerofill']
- ['Features/dht.md', 'Features', 'Distributed Hash Tables']
- ['Features/heal-info-and-split-brain-resolution.md', 'Features', 'heal info and split brain resolution']
- ['Features/libgfapi.md', 'Features', 'libgfapi']
- ['Features/mount_gluster_volume_using_pnfs.md', 'Features', 'Mount Gluster Volume using pNFS']
- ['Features/nufa.md', 'Features', 'Non Uniform File Access']
- ['Features/ovirt-integration.md', 'Features', 'ovirt integration']
- ['Features/qemu-integration.md', 'Features', 'qemu integration']
- ['Features/rdmacm.md', 'Features', 'RDMA Connection Manager']
- ['Features/rebalance.md', 'Features', 'Rebalance']
- ['Features/server-quorum.md', 'Features', 'Server Quorum']
- ['Features/worm.md', 'Features', 'Write Once Read Many']
- ['Features/distributed-geo-rep.md', 'Features', 'Distributed Geo Replication']
- ['Features/libgfchangelog.md', 'Features', 'libgf Changelog']

theme: readthedocs